- app/models/constituency_petition_journal.rb
- app/models/domain.rb
- app/models/invalidation.rb
- app/models/petition.rb
- app/models/signature.rb
- config/application.rb
- spec/factories.rb
- spec/models/invalidation_spec.rb
- spec/models/member_spec.rb
- spec/models/signature_spec.rb
In Rails 5.2, the belongs_to association is required by default so we need to mark some as optional. We also need to tweak the factories and some test setup to ensure we meet the new requirements.
> Enforce Rails 5.2 defaults

- Rakefile
- lib/package_builder.rb
Start from a clean slate by surcharging `db:migrate` to load the
database schema if it doesn't exist.
Co-authored-by: Andrew White <andrew.white@unboxedconsulting.com>
> fix: remove historical migrations

- Gemfile
- Gemfile.lock
The daemonization code was removed in puma/puma#2170 which is the right thing to do but we'll need to switch to a systemd script so lock to a previous version while we get that sorted.
> Lock puma to < 5 whilst we rework init.d script

- app/controllers/petitioners_controller.rb
- app/jobs/email_confirmation_for_creator_email_job.rb
- app/models/petition_creator.rb
- app/models/site.rb
- app/views/petitions/moderation_info.html.erb
- config/locales/notify.en-GB.yml
- config/locales/notify.gd-GB.yml
- config/routes.rb
- features/charlie_creates_a_petition.feature
- features/step_definitions/extra_steps.rb
- features/step_definitions/petition_steps.rb
- spec/controllers/petitioners_controller_spec.rb
- spec/fixtures/notify/2b9f7f53-1f28-446d-9502-cb77d0928f61.yml
- spec/fixtures/notify/cbf205c3-9d3a-4d97-8dd6-c367ecaeb8cd.yml
Scottish parliament does not require any sponsors for a petition to be moderated.
This adds that functionality, without getting rid of the sponsor functionality.
Petition creator will now be emailed to validate their email, and petition goes straight to sponsored state, once they have confirmed.
> Allow sponsor count to be zero

- .github/workflows/build.yml
- .github/workflows/preview.yml
Under active development there may be multiple PRs being merged in rapid succession and each of these will trigger a deploy currently and there may be failures as only one deploy will work at a time.
By switching to deploying on release we can control when the deploy happens and batch up a group of changes to deployed at the same time.
The trigger is when the release is 'created' with the idea that we will create draft releases that deploy to preview automatically and then when we have a production environment we will publish the release to deploy to production.
> Adjust trigger for deploying to preview

- app/views/petitions/check.html.erb
- app/views/petitions/thank_you.html.erb
- config/locales/ui.en-GB.yml
- config/locales/ui.gd-GB.yml
- features/charlie_creates_a_petition.feature
Scottish Parliament does not require petitions to collect sponsors, so this should not be shown as a warning in the create a petition journey
> Hide section that warns petitioners about the need to collect sponsors

- app/controllers/petitioners_controller.rb
Previously the email verification link was redirecting to the wrong page because the signature count had not been updated in time. This does it immediately, ensuring the petitioner gets sent to the correct page
> Update signature count immediately on verification

- app/models/signature.rb
- features/step_definitions/admin_search_steps.rb
- features/step_definitions/petition_steps.rb
- features/step_definitions/signature_steps.rb
- features/suzie_signs_a_petition.feature
- spec/factories.rb
- spec/jobs/petition_count_job_spec.rb
- spec/jobs/update_signature_counts_job_spec.rb
- spec/models/constituency_petition_journal_spec.rb
- spec/models/country_petition_jounal_spec.rb
- spec/models/petition_spec.rb
- spec/models/signature_spec.rb
In a number of places we are doing hacky things to ensure petitions are in a consistent state for the tests we're doing. This commit removes most of those aside from instances where we're checking things like signature counting jobs, invalidation, etc.
This also picked up a few places where the test setup was incorrect.
> Make factories (mostly) consistent

- config/application.rb
Now that primary keys have been changed to bigints we no longer need to default the migration generator to use the old :serial format.
> Remove obsolete generator primary key config

- app/jobs/concerns/session_advisory_lock.rb
- app/jobs/update_signature_counts_job.rb
- config/initializers/delayed_job_config.rb
- spec/jobs/update_signature_counts_job_spec.rb
When the RDS service did a security update the inability of delayed_job to recover from connection errors led to two instances of the counting job being enqueued as there's a task that runs every 15 minutes to ensure it's running. When delayed_job was restarted after log rotation this unlocked the original job and resulted in both jobs being processed and signatures being double counted for a short period.
This commit tries to prevent this from reoccurring in the future by using PostgreSQL advisory locks to ensure that two jobs can't run concurrently in the same way Active Record uses them to prevent migrations from being run concurrently. Given this restriction we can put the count job onto it's own queue and if we detect there is more than
one job on the queue then skip processing and …
> Make signature counting more robust

- app/controllers/petitioners_controller.rb
- app/views/petitioners/thank_you.html.erb
- config/routes.rb
- spec/controllers/petitioners_controller_spec.rb
Instead of using the signatures/thank-you, the petitioners controller now redirects to its own thank-you url
> Redirect to new thank you

- .github/workflows/staging.yml
- lib/tasks/deploy.rake
A staging environment will allow for more experimental changes such as removing Notify to be tested without breaking the preview environment which will needed to test out content changes in the next sprint.
> Add a staging environment

- Gemfile.lock
- lib/package_builder.rb
As of v1.11.0, nokogiri started shipping native gems but to get this to work with developing on a Mac (x86 or ARM) we need to add the plaforms to the lockfile and tweak our package building to include the linux version which our servers need. This makes our package about 15MB larger but ours is relatively small any way (45MB after this change).
> Add platform specific versions of nokogiri

- app/views/admin/petitions/index.html.erb
- app/views/petitions/_content.html.erb
In the admin panel, the table refers to them as "References"
In the frontend, they are presented as "PE1234: Petition action"
> Tweak the way we present PP/PE numbers

- app/assets/stylesheets/frontend/forms.scss
- app/controllers/admin/signatures_controller.rb
- app/controllers/signatures_controller.rb
- app/models/paper_petition.rb
- app/models/petition_creator.rb
- app/models/signature.rb
- app/views/petitions/create/_creator_stage.html.erb
- app/views/petitions/create/_replay_email_stage.html.erb
- app/views/signatures/_email_form.html.erb
- app/views/signatures/_form.html.erb
- config/locales/ui.en-GB.yml
- config/locales/ui.gd-GB.yml
- features/charlie_creates_a_petition.feature
- features/step_definitions/rate_limit_steps.rb
- features/step_definitions/signature_steps.rb
- features/step_definitions/sponsor_steps.rb
- spec/controllers/petitions_controller_spec.rb
- spec/controllers/signatures_controller_spec.rb
- spec/controllers/sponsors_controller_spec.rb
- spec/factories.rb
- spec/models/signature_spec.rb
Petitioners must acknowledge the privacy policy before creating their petition
https://trello.com/c/Ojx8IaD2/50-as-a-petition-creator-or-petitions-clerk-i-want-to-confirm-understanding-of-the-sp-privacy-notice
> Add confirmation for privacy notice

- app/views/petitions/_closed_petition_show.html.erb
- app/views/petitions/_petition.json.jbuilder
- app/views/petitions/index.csv.ruby
https://trello.com/c/TQ6WWkBw/109-as-a-petitioner-signee-member-of-the-public-clerk-i-want-to-see-the-petitioners-name
Petition creator's name should be viewable everywhere, apart from on rejected petitions. But since those are hidden anyway, doesn't really affect this.
> Show petition creator name on all statuses and on csv/json

- config/locales/ui.en-GB.yml
- config/locales/ui.gd-GB.yml
This prevents the user's filled in data from being lost when they click on the privacy notice, though is not ideal for accessibility and use on mobile.
> Open privacy notice read check in separate tab

- app/controllers/admin/petitions_controller.rb
- app/jobs/email_confirmation_for_creator_email_job.rb
- spec/controllers/admin/petitions_controller_spec.rb
When we're not collecting signatures the correct email to resend is the validate signature email and not the gather sponsors email.
The rate limiting inside the email job has been removed as this is handled within the petition creator form directly.
We also don't send a copy to the feedback address as moderators can validate petition creators signatures directly - the copy of the gather sponsors email is sent so that moderators could have access to the 'Sponsor this petition' link.
> Resend the correct email to petition creators

- app/lib/notifications/event.rb
- spec/lib/notifications/event_spec.rb
By making the event inherit from Hash, Appsignal will log the full event details which will make things easier to debug if there are any problems.
> Make Notifications::Event quack like a hash

- app/controllers/admin/take_down_controller.rb
- app/models/petition.rb
- app/views/admin/moderation/_form.html.erb
- config/locales/activerecord.en-GB.yml
- spec/factories.rb
- spec/jobs/notify_everyone_of_failure_to_get_enough_signatures_job_spec.rb
- spec/jobs/notify_everyone_of_moderation_decision_job_spec.rb
- spec/models/constituency_petition_journal_spec.rb
- spec/models/country_petition_jounal_spec.rb
- spec/models/petition_spec.rb
- spec/models/signature_spec.rb
You can't just return false from inside a transaction as you need to raise an exception to generate the rollback.
> Make moderation more robust against errors

- app/controllers/admin/completion_date_controller.rb
- app/controllers/admin/moderation_controller.rb
- app/controllers/admin/notes_controller.rb
- app/controllers/admin/petition_tags_controller.rb
- app/controllers/admin/petition_topics_controller.rb
- app/controllers/admin/schedule_debate_controller.rb
- app/controllers/admin/scot_parl_link_controller.rb
- app/controllers/admin/take_down_controller.rb
- app/models/petition.rb
- app/validators/date_validator.rb
- app/views/admin/completion_date/_petition_action_completion_date.html.erb
- app/views/admin/debate_outcomes/_petition_action_debate_outcome.html.erb
- app/views/admin/petitions/_petition_details.html.erb
- app/views/admin/petitions/index.html.erb
- app/views/admin/schedule_debate/_petition_action_debate_date.html.erb
- app/views/admin/take_down/_petition_action_change_rejection_status.html.erb
- app/views/admin/take_down/_petition_action_take_down.html.erb
- config/locales/activerecord.en-GB.yml
- config/locales/admin.en-GB.yml
- features/suzie_views_a_petition.feature
- spec/controllers/admin/completion_date_controller_spec.rb
- spec/controllers/admin/moderation_controller_spec.rb
- spec/controllers/admin/notes_controller_spec.rb
- spec/controllers/admin/petition_tags_controller_spec.rb
- spec/controllers/admin/petition_topics_controller_spec.rb
- spec/controllers/admin/schedule_debate_controller_spec.rb
- spec/controllers/admin/scot_parl_link_controller_spec.rb
- spec/controllers/admin/take_down_controller_spec.rb
As the number of actions on the petition page has increased any forms with errors are being pushed down the page. This results in moderators not seeing that there was an error and relying on them seeing there's no green notice and its significance. Adding red alerts when the update fails makes it easier for the moderators to see something has gone wrong and where a failure shouldn't happen we advise them to contact us.
> Add flash alert messages to the top of the admin pages

- app/controllers/concerns/flash_i18n.rb
- app/controllers/localized_controller.rb
- app/controllers/signatures_controller.rb
- app/controllers/sponsors_controller.rb
- app/views/petitions/gathering_support.html.erb
- app/views/petitions/moderation_info.html.erb
- config/locales/ui.en-GB.yml
- config/locales/ui.gd-GB.yml
- spec/controllers/signatures_controller_spec.rb
- spec/controllers/sponsors_controller_spec.rb
These messages are rare - the only ones that might possibly be seen without url hacking is someone clicking an old signature verification link or a direct link to the new signature page which is discouraged as someone should read the petition before signing it.
> Move public flash messages to locale files

- app/controllers/admin/petition_details_controller.rb
- app/models/petition.rb
- app/views/admin/petitions/_petition_content.html.erb
- app/views/petitions/_content.html.erb
- app/views/petitions/_petition.json.jbuilder
- features/step_definitions/pickle_steps.rb
- features/suzie_views_a_petition.feature
- spec/models/petition_spec.rb
- spec/requests/petition_show_spec.rb
This has not been localized and isn't currently used so we need to stop using the column in the app before we can add localized columns.
> Remove 'Committee Note' feature

- db/migrate/20210418070355_increase_feedback_ip_address_size.rb
- db/schema.rb
- spec/models/feedback_spec.rb
The UK site only allows ipv4 so the rate limiting added to feedback messages in alphagov/e-petitions@bd8e8fe breaks on the Welsh site as its CloudFront distribution allows ipv6 addresses.
> Allow ipv6 addresses for feedback messages

- features/charlie_is_notified_about_sponsors_signing_his_petition.feature
- features/step_definitions/common_steps.rb
- features/step_definitions/sponsor_steps.rb
- features/step_definitions/sponsor_support_notification_steps.rb
- features/support/hooks.rb
This was fixed as part of SeneddCymru/e-petitions#19 so we're adding the test case from alphagov/e-petitions#812 to prevent a regression.
> Prevent multiple emails when on sponsor threshold

- app/models/petition.rb
- spec/models/petition_spec.rb
If a petition has been scheduled for a debate, has been debated, or a decision to not debate it has been taken then don't reset the `debate_state` column to an incorrect value.
> Ensure correct debate state

- lib/package_builder/config/appspec.yml
Only the AfterInstall phase takes any appreciable amount of time so reduce the timeouts to one minute. The AfterInstall phase is left at 15 minutes to give us time to see what happened and prevent EC2 creating new instances every few minutes.
> Set timeouts for deployment phases

- app/controllers/petitions_controller.rb
- spec/requests/petitions_list_spec.rb
State "collecting signatures" no longer exists, so if someone depends on the API and doesn't change it, it will still work and redirect them to "under consideration" which is the equivalent state now.
> Add backwards compatibility for API

- config/schedule.rb
- lib/tasks/petitions.rake
The ClosePetitionsJob was removed in #161.
NOTE: When deploying to production the changes in #161 we will need to remove any existing queued jobs that have had their job classes removed otherwise Delayed Job will repeatedly try to run them until the max retries limit has been reached.
> Don't try to schedule removed job

- app/models/petition.rb
- app/presenters/petition_csv_presenter.rb
- app/views/petitions/_closed_petition_show.html.erb
- config/locales/ui.en-GB.yml
- config/locales/ui.gd-GB.yml
- spec/presenters/petition_csv_presenter_spec.rb
- Check for closing date before comparing closing date when publishing a petition
- Use open_at date for under_consideration_at in petition CSV downloads
- Fix notification boxes' wording on the closed petition show page
> More fixes after UAT 

- db/migrate/20230103152832_reassign_collecting_signature_petitions_to_under_consideration.rb
- db/migrate/20230130124656_unset_closed_at_date_on_open_petitions.rb
- db/schema.rb
Petitions in the previous version of the site would have their closed_at dates set when opened, and so in the new version would appear closed.
This unsets that so their state remains open
> Unset closed_at date on open petitions

- app/views/petitions/_open_petition_show.html.erb
- db/migrate/20230103152832_reassign_collecting_signature_petitions_to_under_consideration.rb
This means that old petitions will not be affected
> Only set referred at to open date if null

- Dockerfile
- app/assets/javascripts/application.js
- app/assets/javascripts/frontend/onready.js
- docker-compose.yml
- docker-entrypoint.sh
This was broken when changing over to the jasmine-selenium-runner for specs.
> Initialise the character counter when the page content is ready

- Gemfile.lock
The current version doesn't support Ruby 3.0 and we need to deploy it before rolling the servers to the upgraded versions.
> Upgrade net-http-persistent gem

- app/jobs/concerns/email_all_petition_signatories.rb
- app/models/invalidation.rb
The former method has been deprecated by Appsignal.
> Replace without_instrumentation with ignore_instrumentation_events

- .github/dependabot.yml
These gems are largely auto-generated from a set of API descriptions and consist of lots of individual gems released at the same time.
> Group updates for the AWS SDK gems
